---
label: Settings
hide_body: true
is_partial: false
fields:
- type: text
  name: title
  label: title
  hidden: true
- type: textarea
  name: hero_text
  label: Hero text
  config:
    wysiwyg: true
    schema:
      format: html
